[workspace]
resolver = "2"

members = ["day-01", "day-02"]

[workspace.dependencies]
aho-corasick = "1.1"
bytes = "1.5"
memchr = { version = "2.7", default-features = false }
nom = "7.1"
rayon = "1.8"
